### ISSUE TITLE
`getIsPortTaken` does not work and break the `usedPortAction` option

### ISSUE THREAD

**Issue by nrako** [playwright-community/jest-process-manager#19]
This following method `getIsPortTaken` might falsely return `false`, even though a server might be running on the configured `protocol`, `host` and `port`. 

https://github.com/playwright-community/jest-process-manager/blob/ff7018a6c747aa370b1e62df1aa16b4a316f4aa6/src/index.ts#L121-L134

This renders `usedPortAction` useless, and for example would lead to a server being started while `ignore` should have prevented that.

From what I understood this is because of [SO_REUSEADDR and SO_REUSEPORT](https://stackoverflow.com/questions/19129570/how-can-i-check-if-port-is-busy-in-nodejs):

Package such as `node-portscanner` would use `net.Socket()` to prevent that: https://github.com/baalexander/node-portscanner/blob/4fc93fe2a5cc9db983caab57bfe27cbee4de9cc5/lib/portscanner.js#L100-L135

**Comment by mmarkelov** [comment]
@nrako thanks for report! I'll try to investigate this soon
