### ISSUE TITLE
Misleading documentation about protocols

### ISSUE THREAD

**Issue by drakulavich** [playwright-community/jest-process-manager#20]
Taking the first steps with `playwright`. Was stuck with one part of the documentation:
https://github.com/playwright-community/jest-process-manager#protocol

Turned out that it's not a protocol. It's a "resource prefix" from [wait-on](https://www.npmjs.com/package/wait-on) library.
So, `http` means HTTP HEAD returns 2XX response. In my case, I had to change it to `http-get` to work properly.

Please, mention `wait-on` in readme explicitly.

**Comment by mmarkelov** [comment]
@drakulavich yeah! I'm agree with you. I'll try to write it in cleaner way
