### ISSUE TITLE
getIsPortTaken not working?

### ISSUE THREAD

**Issue by Rendez** [playwright-community/jest-process-manager#23]
While my CRA is running on 3000:
```sh
$ lsof -i:3000
COMMAND   PID   USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    61083 xxx   28u  IPv4 0xadaa3c4d20d19779      0t0  TCP *:hbci (LISTEN)
```
Seems like no error is triggered on:
```js
net_1.default
            .createServer()
            .once('error', (err) => err.code === 'EADDRINUSE' ? resolve(cleanupAndReturn(true)) : reject()) // <--- doesn't go here
            .once('listening', () => resolve(cleanupAndReturn(false))) // <--- goes here
            .listen(config.port, config.host);
```

If running the above JS snippet on a REPL twice, it indeed will report `EADDRINUSE` the second time. How is this possibe?

**Comment by Rendez** [comment]
CRA seems to report: `Something is already running on port 3000.`. so it already does this check, however, the debug output was swallowed.

**Comment by mmarkelov** [comment]
@Rendez thank you for report! I just released new version, with new implementation of **getIsPortTaken** function. Can you check it out?

**Comment by Rendez** [comment]
It works perfectly. Thank you!
